### PR TITLE
add German Translation to Android App

### PR DESCRIPTION
**Pull request by thestealth131205**
here an German Translation for the Android app 

[values-de-rDE.zip](https://github.com/voroshkov/Chorus-RF-Laptimer/files/1487082/values-de-rDE.zip)

### CODE REVIEW

**Comment by voroshkov** [comment]
@thestealth131205, Are you ok if I send the translation to the FB group to check if it's accepted by other native speakers as well?

**Comment by thestealth131205** [comment]
Perfect

**Comment by thestealth131205** [comment]
oh i see i have bluetooth in two strings.
[values-de-rDE.zip](https://github.com/voroshkov/Chorus-RF-Laptimer/files/1487080/values-de-rDE.zip)

**Comment by anunique** [comment]
<string name="menu_disconnect">Verbindung trennen</string> 
<string name="setup_clear_threshold">zurücksetzen</string>
<string name="setup_min_lap_time">mindeste Rundenzeit</string>
<string name="setup_skip_first_lap">erste Runde ignorieren</string>
<string name="setup_enable_device_sounds">Geräte Töne</string>
<string name="freq_rf_band">Frequenzband</string>
<string name="stop_race">Rennen anhalten ( lange drücken )</string>
<string name="best_lap_position">Beste Runden Position %s</string>
<string name="disconnected">Verbindung getrennt</string>

    
    <string name="report_file_name">Bericht gespeichert als: %s</string>
    <string name="report_failure">Berichterstellung fehlgeschlagen. Bitte prüfen, ob genug Speicher vorhanden ist.</string>

    
    <string name="battery_status_critical">Gerätespannung kritisch</string>
    <string name="battery_status_low">Gerätespannung niedrig</string>

    <plurals name="pilots_in_race">
        <item quantity="one">Starte Rennen (%1$d Pilot)</item>
        <item quantity="other">Starte Rennen (%1$d Piloten)</item>
    </plurals>

    <plurals name="minutes">
        <item quantity="one">%1$d Minute</item>
        <item quantity="other">%1$d Minuten</item>
    </plurals>

**Comment by thestealth131205** [comment]
sorry no time for this i have add this in android studio not per xml the xml is writen by android studio.

**Pull request closed without merging**
