### PR TITLE
Power saving on inactive modules

### PR DESCRIPTION
**Pull request by voroshkov**

### CODE REVIEW

**Comment by JyeSmith** [comment]
What current drop are you getting after powering down?

**Comment by voroshkov** [comment]
@Smeat Unfortunately this doesn't compile because SERIAL_ENABLE_HIGH and SERIAL_ENABLE_LOW are not defined in Arduino code

**Comment by Smeat** [comment]
My code was based on the (then) current master, where those were still present.
I've updated my branch to compile with the newest changes.

I also fixed a wrong register in my reset function and in the "PowerDownFeatures" function, which wrote to the "Receiver Control Register 1". Since this is in current master you might want to fix/test this.

I am quite busy this week, but will hopefully manage to test my changes in the following week.

**Comment by voroshkov** [comment]
It seems to work. Thank you!

**Comment by voroshkov** [comment]
How should I write your name in the "Contributors" section of the Readme ? :)

**Comment by Smeat** [comment]
Glad to hear it is working

> How should I write your name in the "Contributors" section of the Readme ? :)

Perfectly fine, like it's now. Thank you very much :)

**Pull request merged**
